# Generated by Django 5.1.1 on 2024-09-18 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время последнего изменения')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО сотрудника')),
                ('position', models.CharField(max_length=100, verbose_name='Должность сотрудника')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отдел сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время последнего изменения')),
                ('name', models.CharField(max_length=300, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('deadline', models.DateTimeField(verbose_name='Срок выполнения')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('assigned', 'Назначен исполнитель'), ('in_progress', 'В работе'), ('finished', 'Завершена')], default='created', max_length=100, verbose_name='Статус задачи')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.employee', verbose_name='Сотрудник')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.task', verbose_name='Связанная задача')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
