# Generated by Django 5.1.1 on 2024-09-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_task_employee_task_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employees',
        ),
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='task',
            name='employees_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='tracker.employee', verbose_name='Список сотрудников'),
        ),
    ]
