# Generated by Django 5.1.1 on 2024-09-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_task_employees_task_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employees_list',
        ),
    ]
