# Generated by Django 5.1.1 on 2024-09-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_task_employees_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('in_progress', 'В работе'), ('finished', 'Завершена'), ('overdue', 'Просрочена')], default='created', max_length=100, verbose_name='Статус задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='tracker.employee', verbose_name='Сотрудник'),
        ),
    ]
