# Generated by Django 5.1.1 on 2024-09-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_task_employee_alter_task_status_task_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=100, verbose_name='Приоритет задачи'),
        ),
    ]
