# Generated by Django 5.1.1 on 2024-09-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ManyToManyField(to='tracker.employee', verbose_name='Сотрудник'),
        ),
    ]
