# Generated by Django 5.1.1 on 2024-09-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_task_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='tracker.employee', verbose_name='Сотрудник'),
        ),
    ]
