# Generated by Django 5.1.1 on 2024-09-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_task_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ManyToManyField(to='tracker.employee', verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('finished', 'Завершена'), ('overdue', 'Просрочена')], default='created', max_length=100, verbose_name='Статус задачи'),
        ),
    ]
