# Generated by Django 5.1.1 on 2024-09-24 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_task_employee_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('in_progress', 'В работе'), ('finished', 'Завершена'), ('overdue', 'Просрочена')], default='created', max_length=100, verbose_name='Статус задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='tracker.employee', verbose_name='Сотрудник'),
        ),
    ]
