# Generated by Django 5.1.1 on 2024-09-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rename_name_task_title_remove_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=100, verbose_name='Приоритет задачи'),
        ),
    ]
