# Generated by Django 5.1.1 on 2024-10-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(
                help_text="ДД.ММ.ГГГГ 00:00", verbose_name="Срок выполнения"
            ),
        ),
    ]
